# 根据需求添加相对应的role
- src: http://github.com/pucilpet/role_common

- src: http://github.com/websoft9/role_cloud

- src: http://github.com/websoft9/role_apache

- src: http://github.com/websoft9/role_nginx

- src: http://github.com/websoft9/role_mysql

- src: http://github.com/websoft9/role_php

- src: http://github.com/websoft9/role_docker

- src: http://github.com/websoft9/role_init

- src: http://github.com/websoft9/role_preend

- src: http://github.com/websoft9/role_end

- src: http://github.com/websoft9/role_9panel

- src: http://github.com/websoft9/role_inotify_watch

- src: http://github.com/websoft9/role_redis
